-- Safe ABK salary correction/deletion and expedition BOP removal.
create or replace function public.finance_correct_abk_salary_v1(
  p_id uuid,
  p_gross_salary numeric,
  p_advance_deduction numeric,
  p_paid_on date,
  p_notes text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_salary public.abk_cycle_salaries%rowtype;
  v_remaining numeric;
  v_balance numeric;
  v_take numeric;
  v_adv record;
begin
  if not exists (
    select 1 from public.profiles p
    where p.user_id=auth.uid() and p.active and p.role in ('ADMIN','KEUANGAN')
  ) then raise exception 'Akses ditolak.'; end if;

  select * into v_salary from public.abk_cycle_salaries where id=p_id for update;
  if v_salary.id is null then raise exception 'Transaksi gaji tidak ditemukan.'; end if;
  if p_gross_salary is null or p_gross_salary<0 then raise exception 'Gaji bruto tidak valid.'; end if;
  if p_advance_deduction is null or p_advance_deduction<0 or p_advance_deduction>p_gross_salary then
    raise exception 'Potongan kasbon tidak valid.';
  end if;
  if p_paid_on is null then raise exception 'Tanggal bayar wajib.'; end if;

  -- Remove only the automatic deductions generated by this unique ABK/cycle salary.
  delete from public.advance_payments ap
  where ap.method='POTONG_GAJI'
    and ap.paid_on=v_salary.paid_on
    and ap.notes='Potongan otomatis dari gaji siklus'
    and ap.advance_id in (
      select a.id from public.advances a
      where a.employee_id=v_salary.abk_id
        and a.contract_assignment_id=v_salary.contract_assignment_id
    );

  select coalesce(sum(a.amount-coalesce(p.paid,0)),0)
  into v_balance
  from public.advances a
  left join (
    select advance_id,sum(amount) paid
    from public.advance_payments
    group by advance_id
  ) p on p.advance_id=a.id
  where a.employee_id=v_salary.abk_id
    and a.contract_assignment_id=v_salary.contract_assignment_id;

  if p_advance_deduction>v_balance then
    raise exception 'Potongan kasbon melebihi saldo kasbon. Saldo Rp %.',v_balance;
  end if;

  update public.abk_cycle_salaries
  set gross_salary=p_gross_salary,
      advance_deduction=p_advance_deduction,
      net_paid=p_gross_salary-p_advance_deduction,
      paid_on=p_paid_on,
      notes=nullif(trim(coalesce(p_notes,'')),'')
  where id=p_id;

  update public.bop
  set incurred_on=p_paid_on,
      amount=p_gross_salary,
      notes='Gaji bruto ABK per siklus'
  where source_type='ABK_SALARY' and source_id=p_id;

  v_remaining:=p_advance_deduction;
  for v_adv in
    select a.id,a.amount-coalesce(p.paid,0) as balance
    from public.advances a
    left join (
      select advance_id,sum(amount) paid
      from public.advance_payments
      group by advance_id
    ) p on p.advance_id=a.id
    where a.employee_id=v_salary.abk_id
      and a.contract_assignment_id=v_salary.contract_assignment_id
      and a.amount-coalesce(p.paid,0)>0
    order by a.advanced_on,a.created_at,a.id
  loop
    exit when v_remaining<=0;
    v_take:=least(v_remaining,v_adv.balance);
    insert into public.advance_payments(advance_id,paid_on,amount,method,reference,notes)
    values(v_adv.id,p_paid_on,v_take,'POTONG_GAJI',null,'Potongan otomatis dari gaji siklus');
    v_remaining:=v_remaining-v_take;
  end loop;

  return true;
end $$;

create or replace function public.admin_delete_abk_salary_v1(p_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_salary public.abk_cycle_salaries%rowtype;
  v_old jsonb;
begin
  if not exists (
    select 1 from public.profiles p
    where p.user_id=auth.uid() and p.active and p.role='ADMIN'
  ) then raise exception 'Hanya ADMIN yang boleh menghapus transaksi gaji.'; end if;

  select * into v_salary from public.abk_cycle_salaries where id=p_id for update;
  if v_salary.id is null then raise exception 'Transaksi gaji tidak ditemukan.'; end if;
  v_old:=to_jsonb(v_salary);

  delete from public.advance_payments ap
  where ap.method='POTONG_GAJI'
    and ap.paid_on=v_salary.paid_on
    and ap.notes='Potongan otomatis dari gaji siklus'
    and ap.advance_id in (
      select a.id from public.advances a
      where a.employee_id=v_salary.abk_id
        and a.contract_assignment_id=v_salary.contract_assignment_id
    );

  delete from public.bop
  where source_type='ABK_SALARY' and source_id=p_id;

  delete from public.abk_cycle_salaries where id=p_id;

  insert into public.audit_events(actor,action,table_name,record_id,old_data,new_data)
  values(auth.uid(),'DELETE_ADMIN','abk_cycle_salaries',p_id::text,v_old,null);

  return true;
end $$;

create or replace function public.admin_delete_expedition_trip_bop_v1(p_trip_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old jsonb;
  v_count int;
begin
  if not exists (
    select 1 from public.profiles p
    where p.user_id=auth.uid() and p.active and p.role='ADMIN'
  ) then raise exception 'Hanya ADMIN yang boleh menghapus BOP Expedisi.'; end if;

  select jsonb_agg(to_jsonb(b)) into v_old
  from public.finance_expedition_bop b
  where b.trip_id=p_trip_id and b.reference='AUTO_TRIP';

  if v_old is null then raise exception 'BOP trip tidak ditemukan.'; end if;

  delete from public.finance_expedition_bop
  where trip_id=p_trip_id and reference='AUTO_TRIP';
  get diagnostics v_count=row_count;

  insert into public.audit_events(actor,action,table_name,record_id,old_data,new_data)
  values(auth.uid(),'DELETE_ADMIN','finance_expedition_bop',p_trip_id::text,v_old,null);

  return v_count>0;
end $$;

revoke all on function public.finance_correct_abk_salary_v1(uuid,numeric,numeric,date,text) from public,anon;
revoke all on function public.admin_delete_abk_salary_v1(uuid) from public,anon;
revoke all on function public.admin_delete_expedition_trip_bop_v1(uuid) from public,anon;
grant execute on function public.finance_correct_abk_salary_v1(uuid,numeric,numeric,date,text) to authenticated;
grant execute on function public.admin_delete_abk_salary_v1(uuid) to authenticated;
grant execute on function public.admin_delete_expedition_trip_bop_v1(uuid) to authenticated;
